image: node:8
stages:
  - test
  - publish
  - push-github

.test: &test
  stage: test
  script:
   - npm install
   - npm run test

Test Node 8:
  image: node:8
  <<: *test

Test Node 9:
  image: node:9
  <<: *test

Test Node 10:
  image: node:10
  <<: *test

Test Node 11:
  image: node:11
  <<: *test

Publish:
  stage: publish
  only:
    - tags
  script:
    - echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" >> ~/.npmrc
    - npm publish

PushGitHub:
  stage: push-github
  only:
    - develop
    - master
  script:
    - echo "Push $CI_PROJECT_NAME to GitHub"
    - mkdir $HOME/.ssh
    - cp $CI_ID_RSA $HOME/.ssh/id_rsa
    - cp $CI_ID_RSA_PUB $HOME/.ssh/id_rsa.pub
    - chmod 400 $HOME/.ssh/id_*
    - echo 'ssh -i $HOME/.ssh/id_rsa -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -v $*' > ssh
    - chmod +x ssh
    - GIT_SSH='./ssh' git push github --follow-tags --verbose HEAD:$CI_COMMIT_REF_NAME
