image: node:8
stages:
  - test
  - publish
  - push-github

include:
  # - remote: https://gitlab.noname-media.com/nnmedia/gitlabci/raw/master/gitlab-ci-nodejs.yml
  - project: 'nnmedia/gitlabci'
    file: 'gitlab-ci-nodejs.yml'
